apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    purpose: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: mongodb
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        purpose: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mongodb
          image: yadaveshnithin/mongodb:v1

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    purpose: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    purpose: mongodb
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

