apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    purpose: catalogue
    project: roboshop
    tier: app
data:
  MONGO_URL: "mongodb://mongodb:27017/catalogue" 
  MONGO: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    purpose: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        purpose: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
        - name: catalogue
          image: yadaveshnithin/catalogue:v1
          envFrom:
          - configMapRef:
            name: catalogue


---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    purpose: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    purpose: catalogue
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

